[theme]
base = "light"
primaryColor = "#0EA5E9"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = false

[browser]
gatherUsageStats = false
